version: '3'

services:
  web:
    image: richarvey/nginx-php-fpm:latest
    ports:
      - "$WEB_PORT:80"
    volumes:
      - "$WORK_DIR/html:/var/www/html/"
    networks:
      - web
    restart: unless-stopped
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $IDE_SUDO_PASSWORD
      MYSQL_USER: $USERNAME
      MYSQL_PASS: $IDE_PASSWORD
    volumes:
      - "$WORK_DIR/data:/var/lib/mysql"
    ports:
      - "$DB_PORT:3306"
    networks:
      - web
    restart: unless-stopped
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: $IDE_SUDO_PASSWORD
    ports:
      - "$MAD_PORT:80"
    networks:
      - web
    restart: unless-stopped
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    volumes:
      - "$WORK_DIR/html:/config/code"
      - "$WORK_DIR/logs:/config/logs"
    networks:
      - web
    ports:
      - "$IDE_PORT:8443"
    restart: unless-stopped
    environment:
      - PASSWORD=$IDE_PASSWORD
      - SUDO_PASSWORD=$IDE_SUDO_PASSWORD
      - TZ=America/New_York
      - DEFAULT_WORKSPACE=/config/code
      - PUID=1000
      - GUID=1001
    networks:
      - web

networks:
  web:
    external:
        name: "web"